import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import Komponen Layout
// import Bootstrap from "@/app/layout/bootstrap";
import "react-datepicker/dist/react-datepicker.css";

// Custom Styles
import "../../public/assets/css/style.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      dir="ltr"
      data-bs-theme="light"
      data-color-theme="Blue_Theme"
      data-layout="vertical"
      data-boxed-layout="boxed"
      data-card="shadow"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} link-sidebar`}
        data-sidebartype="full"
      >
        {children}
      </body>
    </html>
  );
}
